# Generated by Django 3.2.9 on 2022-12-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221121_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='dificult',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='articles',
            name='place',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Номер языка'),
        ),
        migrations.AddField(
            model_name='articles',
            name='quantity',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Количество программистов'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
